### ISSUE TITLE
Question: does the phone-ringing animation use spring animation?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [sagar-viradiya/AndroidPhysicsAnimation#1]
I'm talking about this:

![2018-07-11_10-12-59](https://user-images.githubusercontent.com/5357526/42556059-04e7cb40-84f3-11e8-872c-d071f264c8ba.gif)

If not, what does it use?
Can the physics animation library help to do something like that ?
To me it seems it starts from center, and goes left and right of it.

**Comment by sagar-viradiya** [comment]
Hey, Not sure phone ringing animation uses physics animation.

But it is possible using physics animation. It seems like animation is divided into 2 parts

1. Vertical translation
2. Horizontal spring animation

**Comment by AndroidDeveloperLB** [comment]
I just wanted the "wiggling" animation to be smooth and natural. Also not sure how I could do it using the normal API, as it needs to do animation in X coordinate of : 0 -> (-10) -> 10 -> 0

I think I got something similar to what you see on the Phone app:
[RingingWiggleShakeAnimationTest.zip](https://github.com/sagar-viradiya/AndroidPhysicsAnimation/files/2183920/RingingWiggleShakeAnimationTest.zip)

![2018-07-11_12-48-55](https://user-images.githubusercontent.com/5357526/42564265-fff5af1a-8508-11e8-9319-4c0304fd7bc5.gif)

Need some work on this. Still doesn't look so fluid and natural...

**Comment by sagar-viradiya** [comment]
Are using linear interpolator for translation y animation ?

If yes I would recommend some other interpolator to make it smooth

Never mind saw your code. You are using FastOutSlowInInterpolator

**Comment by sagar-viradiya** [comment]
Never mind saw your code. You are using FastOutSlowInInterpolator

**Comment by AndroidDeveloperLB** [comment]
It's a bit hard to see it in the animation here. Not enough FPS...

You can try the sample yourself too.

**Comment by AndroidDeveloperLB** [comment]
It's a bit hard to see it in the animation here. Not enough FPS...
You can try the sample yourself too. 

BTW, I tried to convert your sample to Android-X. Got a weird issue there:
https://issuetracker.google.com/issues/111316650

**Comment by sagar-viradiya** [comment]
Navigation is not compatible with androidx. It will be available in future release.

**Comment by AndroidDeveloperLB** [comment]
How do you know this?

**Comment by sagar-viradiya** [comment]
https://github.com/googlesamples/android-sunflower

Refer ☝️. Sample app showcasing jetpack and this also uses support lib

**Comment by AndroidDeveloperLB** [comment]
Nice. Thanks.
BTW, A gardening app?!
:)
